# Generated by Django 2.1.7 on 2019-04-25 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_formation_latest'),
    ]

    operations = [
        migrations.AddField(
            model_name='latest',
            name='institution',
            field=models.CharField(default='Autonomo', max_length=75),
        ),
    ]
